# Generated by Django 6.0.6 on 2026-07-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(),
        ),
    ]
